import { Inter } from "next/font/google";
import "@/app/globals.css";
import DashboardContentRight from '@/components/organisms/DashboardContentRight';
import SideMenu from '@/components/organisms/SideMenu';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="flex flex-1">
      <SideMenu/>
      <div className="w-full pl-[200px]">
        <div className="lg:flex">
          <div className="w-full">
            {children}
          </div>
          <div className="lg:w-[380px] bg-white min-h-screen lg:overflow-y-auto" >
            <DashboardContentRight/>
          </div>
        </div>
      </div>
    </div>
  );
}
